### ISSUE TITLE
Advertising localhost IP to trusted Prysm node 

### ISSUE THREAD

**Issue by cortze** [probe-lab/hermes#31]
# Description
Hermes currently advertises only the private address when connecting to the local Prysm node. This makes local testing harder, as the Prysm node might not always be on the same local network (target for the production deployment at AWS or similar). 

```go
// register ourselves as a trusted peer by submitting our private ip address
privateMaddr, err := n.host.PrivateListenMaddr()
    if err != nil {
    return err
}

slog.Info("Adding ourselves as a trusted peer to Prysm", tele.LogAttrPeerID(n.host.ID()), "maddr", privateMaddr)
    if err := n.pryClient.AddTrustedPeer(ctx, n.host.ID(), privateMaddr); err != nil {
    return fmt.Errorf("failed adding ourself as trusted peer: %w", err)
}
```

Creating an `SSH` tunnel with the Hermes port reverse-tunneled is convenient. However, this requires the Hermes instance to advertise the `localhost` IP, which opens a few questions:

- Should Hermes also advertise both addresses? it would mean adding two peers as trusted on the Prysm side (with the private connections always failing, or vice-versa)
- Should we just use the localhost one? 
- Should the user choose it with a new flag like: `--local-prysm=true/false`?

**Comment by guillaumemichel** [comment]
What do you mean by _advertise_ the `localhost` IP?

**Comment by guillaumemichel** [comment]
OK I see. Would it be a security issue to have Hermes advertise both addresses? It seems to be the easiest solution.

Alternatively the `--local-prysm=true/false` flag also seems a good option.

**Comment by cortze** [comment]
On the security side, I would say that there is nothing to worry about, as this is just how `Hermes` lets `Prysm` know how to reach it back.

It could indeed advertise both addresses, the `private` and `localhost` ones, but it means that Prysm will constantly try to connect both addresses while one of them is always unreachable 🤷🏽

**Comment by guillaumemichel** [comment]
Alright, then maybe the flag is best in this case

**Comment by cortze** [comment]
> Alright, then maybe the flag is best in this case

Nice, I'll set it to the `private` one as default, and change it to the `localhost` one if the flag `--local-trusted-address` is given
