### ISSUE TITLE
GitHub Actions Run actions/setup-go@v5 fails

### ISSUE THREAD

**Issue by dennis-tra** [probe-lab/hermes#8]
Hi @galargh,

the GitHub Actions fail because they're trying to setup Go version `1.22.0.x` which doesn't exist.

<img width="685" alt="image" src="https://github.com/probe-lab/hermes/assets/11836793/11beebcc-0a89-4853-889a-93dff2e31a39">

Could you help me out here?

**Comment by galargh** [comment]
Great catch! Could we revert specifying the patch version in `go.mod` for now? As per https://github.com/probe-lab/hermes/pull/9

This will give us a bit more time to tackle the issue properly in Unified GitHub Workflows.

**Comment by dennis-tra** [comment]
Ah, I see! Yeah, sure we don't need the patch version in the `go.mod` file :)

**Comment by cortze** [comment]
@galargh what is the latest update on this topic?

Coming from #17
